# Dependencies
markdown:         kramdown 
highlighter:      rouge 

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Thematic Quarter on Causality
tagline:          Causal Inference, Causality, Machine Learning
description:      ''
url:              https://thematic-quarter-causality.github.io
baseurl:          ''
paginate:         20
# paginate_path:    "/blog/page:num/"

author:
  name:           ''
  url:            



plugins: 	  [jekyll-paginate]

# Custom vars
version:          1.0.0
categorylist:     [causal inference, causality, causal networks, causal models, machine learning]
# collections:
#     notes:
#         collections_dir: notes
#         output: true
#         permalink: /notes/:name


github: 
  repo: 
  
# Github flavored markdown
markdown: kramdown
kramdown:
  auto_ids:      true
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  
  input:         GFM
  hard_wrap:     false
  footnote_nr:   1
  show_warnings: false

